/**
 * Share the pure licensing-rule modules with the Cloud Functions runtime.
 *
 * The RAIS email connector (src/rais/ingest.ts) needs the SAME parser the web
 * app uses on the Licensing Status tab. That logic lives in `lib/rules/` and is
 * the single source of truth. Firebase only uploads the `functions/` folder, so
 * this script copies the handful of framework-free files it needs into
 * `functions/src/rais/rules/` right before `tsc` runs.
 *
 * The copies are generated (git-ignored) — never edit them by hand; edit the
 * originals in `lib/rules/` and rebuild. Wired into `npm run build`, which
 * `firebase deploy` runs via the predeploy hook.
 */
const fs = require("fs");
const path = require("path");

// Pure, dependency-free modules the connector imports. Keep this list minimal —
// adding an entry pulls another file (and its imports) into the function bundle.
const FILES = [
  "types.ts",
  // The audit trigger writes the same summaries the app reads back, so the
  // line an officer sees in the panel is written by this exact code.
  "auditLog.ts",
  // types.ts re-exports the cargo vocabulary from here, so the copy does not
  // compile without it. Dependency-free itself.
  "borderCargo.ts",
  "matching.ts",
  "raisTemplates.ts",
  "parseNotifications.ts",
  "supersede.ts",
];

const SRC_DIR = path.resolve(__dirname, "..", "..", "lib", "rules");
const DEST_DIR = path.resolve(__dirname, "..", "src", "rais", "rules");

const BANNER =
  "// AUTO-GENERATED by functions/scripts/sync-rules.js — DO NOT EDIT.\n" +
  "// Source of truth: lib/rules/. Run `npm run build` in functions/ to refresh.\n\n";

function main() {
  for (const file of FILES) {
    const from = path.join(SRC_DIR, file);
    if (!fs.existsSync(from)) {
      throw new Error(`sync-rules: expected source file is missing: ${from}`);
    }
  }

  fs.rmSync(DEST_DIR, { recursive: true, force: true });
  fs.mkdirSync(DEST_DIR, { recursive: true });

  for (const file of FILES) {
    const body = fs.readFileSync(path.join(SRC_DIR, file), "utf8");
    fs.writeFileSync(path.join(DEST_DIR, file), BANNER + body, "utf8");
  }

  console.log(
    `sync-rules: copied ${FILES.length} rule module(s) into ${path.relative(
      process.cwd(),
      DEST_DIR,
    )}`,
  );
}

main();
